### ISSUE TITLE
/

### ISSUE THREAD

**Issue by Decapitater** [lengfengwujing/IWantToRun#1]

**Comment by lengfengwujing** [comment]
I love my country!

**Comment by Decapitater** [comment]
> I love my country!

they making you run ?
enjoy

**Comment by cychan2047** [comment]
> 

Because we are altruist. We spare our great country to let others to enjoy.

**Comment by Decapitater** [comment]
> > 
> 
> Because we are altruist. We spare our great country to let others to enjoy.

sure whatever you like ,
i truly don't give a fuck
