### ISSUE TITLE
Run欧洲

### ISSUE THREAD

**Issue by wang-zhuoran** [lengfengwujing/IWantToRun#3]
想问一下，润欧洲和润美国对比起来怎么样？（也是IT业）后续会不会出run欧洲的教程？

**Comment by lengfengwujing** [comment]
不了解欧洲。。。。。

**Comment by wyx-lab** [comment]
从知乎过来的,想问下京哥各大公司进入的难度，我是学EE的一直想去苹果，英伟达之类的公司，不知道难不难><...
